name: New Integration Request
description: Request a new integration that will connect 2 or more systems.
title: "[New Integration]: "
labels: [ "new integration" ]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details!
  - type: input
    id: team
    attributes:
      label: Team
      description: Which team is requesting this integration?
      placeholder: ex. Finance
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
      Describe what you are trying to achieve or what problem you're trying to solve. Consider what the new integration will enable
      for Shopify or what savings it could provide, and which teams/roles would be impacted by the change. Currently supported systems can be found [here](https://ihub.docs.shopify.io/clients).
      placeholder: Insert text here...
  - type: textarea
    id: impact
    attributes:
      label: Measurable Impact
      description: Provide a measurable amount of time saved through automation. e.g. This task is currently performed 500 times / week, taking 10 minutes per task, resulting in a cost of 5000 minutes / week.
  - type: input
    id: business-process
    attributes:
      label: Current Business Process
      description: Do you have your current business process mapped out for review? If so, provide a link to a description of that process.
  - type: input
    id: vault-link
    attributes:
      label: Vault Link
      placeholder: ex. https://vault.shopify.io/projects/1
  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: Provide any known date by which the integration must be completed.
      placeholder: e.g. January 1st 2021
