name: Onboarding Checklist
description: Checklist for new employees to ensure a smooth onboarding process.
labels: onboarding
body:
  - type: markdown
    attributes:
      value: |
        ## Onboarding Checklist
        Please complete the following tasks to help us get you onboarded smoothly!

  - type: checklist
    id: onboarding_tasks
    attributes:
      title: Tasks
      items:
        - checked: false
          description: [ ] Set up your company email account
        - checked: false
          description: [ ] Complete your profile on the company intranet
        - checked: false
          description: [ ] Join the team chat platform and introduce yourself
        - checked: false
          description: [ ] Review the company policies and handbook
        - checked: false
          description: [ ] Schedule a one-on-one with your manager
        - checked: false
          description: [ ] Set up your work environment and tools

  - type: markdown
    attributes:
      value: |
        Please update the checkboxes as you complete each task!
